# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from swaggerpetstore.api_helper import APIHelper


class StoreControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(StoreControllerTests, cls).setUpClass()
        cls.controller = cls.client.store
        cls.response_catcher = cls.controller.http_call_back

    # Returns a map of status codes to quantities
    def test_get_inventory(self):

        # Perform the API call through the SDK function
        result = self.controller.get_inventory()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


